title: Yuan liaofan
description: yuanliaofan
baseurl: ""
url: "https://yuanliaofan.com"  
repository: liaofanyuan/yuanliaofan

# Language settings
languages: ["en", "zh"]
default_lang: "zh"
exclude_from_localization: ["assets", "css", "js", "images"]
parallel_localization: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .gitignore
  - README.md
  - .DS_Store

defaults:
  - scope:
      path: ""   
      type: "pages"
    values:
      order: 20